r"""mrl-trace: SiO\ :sub:`x` transients as physical eligibility surrogates.

Reference implementation for the manuscript *"Memristive transients as physical
eligibility traces for all-local reinforcement learning"*.  The package
exposes, as small composable pieces:

- :mod:`mrl_trace.device`   -- the empirical current fit, the default nonlinear
  ``CascadeEligibilityGate``, and the explicit linear-Erlang sensitivity;
- :mod:`mrl_trace.neurons`  -- LIF neuron updates (scalar and batched);
- :mod:`mrl_trace.learning` -- the signed coincidence kernel and the
  three-factor reward-modulated update ``dw = eta (R - b) e``;
- :mod:`mrl_trace.bandit`   -- the contextual spiking bandit (the closed-loop
  RL task) with the device gate, an abstract-trace control, and a no-trace control;
- :mod:`mrl_trace.selectivity` -- the interval-selectivity and vector-timer
  tasks that read out the transient's tuning to inter-cue delay;
- :mod:`mrl_trace.extensions`  -- multi-timescale, working-memory + short-term
  consolidation, device-TD and beta-sensitivity extension studies;
- :mod:`mrl_trace.hybrid`   -- the hybrid vision front-end feeding the spiking
  RL readout (raw-pixel orientation task);
- :mod:`mrl_trace.paths`    -- resolves compatible local fixtures and opt-in result
  archives while rejecting scientifically withdrawn archive names.

The ``experiments/`` directory contains notebook-owned live analyses. Corrected
publication-scale statistics require the declared raw fixtures and external seed
archive; they are not bundled or silently reconstructed from historical grids.
"""
from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("mrl-trace")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"
finally:
    del version, PackageNotFoundError

from .device import (
    CascadeEligibilityGate,
    LinearErlangEligibilityGate,
    TransientGate,
    tau_r,
    tau_d,
    BETA,
    K_STAGES,
    fit_kww_laws,
    simulate_habituation,
    KWW_VOLTAGES,
    CASCADE_METHOD_PROVENANCE,
    LINEAR_ERLANG_METHOD_PROVENANCE,
    KWW_METHOD_PROVENANCE,
)
from .neurons import lif_step, lif_step_batched
from .learning import (signed_coincidence, unsigned_coincidence, coincidence_drive,
                       three_factor_update, RewardBaseline, SIGNED_RULE_PROVENANCE,
                       THREE_FACTOR_PROVENANCE)
from .bandit import (
    GateBankBatched,
    LinearErlangGateBankBatched,
    AbstractTrace,
    train,
    reward_rate,
    trials_to_criterion,
    W_INIT,
    W_MAX,
    run_reversal,
    run_reversal_grid,
    calibrate_reversal_scales,
    run_learning_and_window,
    run_scaling,
    run_remedies,
    run_signed_rule_ablations,
    BANDIT_METHOD_PROVENANCE,
)
from .distal_reward import (
    trace_kernel,
    abstract_kernel,
    train_trace_level,
    SpikingGateBank,
    LinearErlangSpikingGateBank,
    train_spiking,
    cue_saturation,
    run_trace_window,
    run_spiking_saturation,
    trace_ratio,
)
from .maze import (
    ActionSequenceTrack,
    DelayedCuedChoice,
    TMaze,
    ConventionalRstdpTrace,
    ShallowEpropPolicyTrace,
    EpropTrace,
    calibrate_comparator_scales,
    tune_comparator_learning_rates,
    run_action_sequence,
    run_delayed_cued_choice,
    run_sequential,
    run_retention_delay_curve,
    run_dmax_law,
    run_retention_delay_curve_adaptive,
    run_dmax_adaptive,
    run_long_horizon,
    run_long_horizon_faults,
    running_rate,
    interp_dmax,
)
from .deep import (
    run_deep_local,
    run_deep_dms,
    calibrate_dms_scales,
    tune_dms_learning_rates,
    run_array_scale,
    run_dms,
    run_dms_all,
    final_rate,
    main,
    DEEP_METHOD_PROVENANCE,
)
from .distal_cue import (run_distal_cue, main as distal_cue_main,
                         DISTAL_CUE_METHOD_PROVENANCE)
from .probselect import (
    run_probselect,
    PST_HP,
    PST_HOMEO,
    PST_SEEDS,
    PST_TRIALS,
    PST_CHANCE,
    PST_CRIT,
    PST_METHOD_PROVENANCE,
)
from .dopamine import (
    DANDISET_ID,
    DANDISET_VERSION,
    DANDI001340_METHOD_PROVENANCE,
    AssetRecord,
    LoggedSession,
    asset_manifest,
    airpls,
    robust_reference_regression,
    preprocess_photometry,
    download_dandi001340,
    prepare_dandi001340,
    load_logged_session,
)
from .model_specs import (
    PRIMARY_MODEL_ID,
    LINEAR_MODEL_ID,
    MODEL_SPEC_SCHEMA_VERSION,
    device_model_spec,
    model_spec_digest,
    known_model_ids,
    select_supported_state_space,
    build_predictive_linkage_manifest,
)
from .predictive_linkage import (
    load_gold_traces,
    candidate_response,
    affine_trace_score,
    fit_candidate,
    score_candidate,
    grouped_held_out_scores,
    bootstrap_held_out_support,
    working_information_criteria,
    bootstrap_kww_parameters,
    score_out_of_domain_candidates,
    default_candidates,
)
from .kernel_theory import (
    linear_pole_rate,
    linear_impulse_peak,
    linear_impulse_response,
    linear_rectangular_response,
    linear_rectangular_peak,
    physical_small_signal_peak,
    simulate_gate_response,
    kernel_phase_map,
    kernel_theory_manifest,
)
from .timing_benchmarks import (
    ABSTRACT_GAMMA_ID,
    MATCHED_EXPONENTIAL_ID as TIMING_MATCHED_EXPONENTIAL_ID,
    MATCHING_REGIMES,
    frozen_kernel_bank,
    matching_scales,
    build_interval_attribution_trials,
    build_temporal_order_trials,
    run_matched_timing_benchmark,
)
from .falsification import build_falsification_predictions
from .codesign import (
    TEMPORAL_BENCHMARK_SCHEMA_VERSION,
    LEARNED_BASIS_ID,
    MATCHED_EXPONENTIAL_ID,
    DEFAULT_RETENTION_DEFINITIONS,
    TEMPORAL_CODESIGN_PROVENANCE,
    eligibility_kernel,
    preferred_lag,
    build_temporal_attribution_trials,
    fit_learned_temporal_basis,
    run_temporal_attribution_benchmark,
    structural_resource_table,
    digital_cost_equivalent,
    timing_phase_envelope,
    build_codesign_reference,
    write_codesign_artifacts,
    render_codesign_figure,
)
from .dopamine_replay import (
    REPLAY_CONDITIONS,
    ReplayParameters,
    trial_modulators,
    run_logged_replay,
    evaluate_logged_replay_loso,
    write_replay_artifacts,
)
from .coddington import (
    CODDINGTON_ARTICLE_DOI,
    CODDINGTON_DATA_DOI,
    CODDINGTON_EXPECTED_MD5,
    CODDINGTON_GROUPS,
    CoddingtonSubject,
    load_coddington_dataset,
    evaluate_coddington_causal_learning,
    write_coddington_tex_macros,
    write_coddington_artifacts,
)
from .jeong import (
    JEONG_DANDISET_ID,
    JEONG_ARTICLE_DOI,
    JEONG_SOURCE_CODE_URL,
    JEONG_CONTROL_SUBJECTS,
    JEONG_INHIBITED_SUBJECTS,
    fetch_jeong000351_manifest,
    load_jeong000351_manifest,
    evaluate_jeong_directional_learning,
    write_jeong_artifacts,
    write_jeong_tex_macros,
)
from .biosignal import (
    load_subject as load_eeg_subject,
    epoch_feedback,
    rewp_features,
    decode_reward as decode_eeg_reward,
    FRONTOCENTRAL,
    EEG_METHOD_PROVENANCE,
)
from .selectivity import (
    run_interval_selectivity,
    run_vector_timer,
    peak_lag,
    selectivity_ratio,
    aliasing_pair,
    run_interval,
    SELECTIVITY_METHOD_PROVENANCE,
    PREDICTIVE_DELAY_GRID,
)
from .extensions import (
    run_multitimescale,
    run_wm_stc,
    wm_isolated,
    run_device_td,
    run_beta_sensitivity,
    load_measured_tau,
    CHANCE,
    CRIT,
    TAU_BAND,
    BETAS,
    V_INIT,
    V_MAX,
    ETA_V,
    EXTENSIONS_METHOD_PROVENANCE,
    RETENTION_DELAY_METHOD_PROVENANCE,
)
from .hybrid import (
    IMG,
    C,
    NOISE,
    make_grating,
    make_batch,
    run_frontend,
    run_readout_pool,
    run_hybrid_decision,
    prep_readouts,
    run_hybrid_scale,
    final_rate as hybrid_final_rate,
    HYBRID_METHOD_PROVENANCE,
)
from .stats import bootstrap_ci, summarise
from . import paths
from .paths import (
    data_dir, results_dir, device_model_dir, ITO_PRIMARY_ACQUISITION_DATES,
    ITO_SUPPLEMENTAL_NEAR_ZERO_FILENAMES, select_ito_source_cohort,
    publication_device_preflight, save_result, load_result,
)

__all__ = [
    "__version__",
    # device
    "CascadeEligibilityGate",
    "LinearErlangEligibilityGate",
    "TransientGate",
    "tau_r",
    "tau_d",
    "BETA",
    "K_STAGES",
    "fit_kww_laws",
    "simulate_habituation",
    "KWW_VOLTAGES",
    "CASCADE_METHOD_PROVENANCE",
    "LINEAR_ERLANG_METHOD_PROVENANCE",
    "KWW_METHOD_PROVENANCE",
    "PRIMARY_MODEL_ID",
    "LINEAR_MODEL_ID",
    "MODEL_SPEC_SCHEMA_VERSION",
    "device_model_spec",
    "model_spec_digest",
    "known_model_ids",
    "select_supported_state_space",
    "build_predictive_linkage_manifest",
    "load_gold_traces",
    "candidate_response",
    "affine_trace_score",
    "fit_candidate",
    "score_candidate",
    "grouped_held_out_scores",
    "bootstrap_held_out_support",
    "working_information_criteria",
    "bootstrap_kww_parameters",
    "score_out_of_domain_candidates",
    "default_candidates",
    "linear_pole_rate",
    "linear_impulse_peak",
    "linear_impulse_response",
    "linear_rectangular_response",
    "linear_rectangular_peak",
    "physical_small_signal_peak",
    "simulate_gate_response",
    "kernel_phase_map",
    "kernel_theory_manifest",
    "ABSTRACT_GAMMA_ID",
    "TIMING_MATCHED_EXPONENTIAL_ID",
    "MATCHING_REGIMES",
    "frozen_kernel_bank",
    "matching_scales",
    "build_interval_attribution_trials",
    "build_temporal_order_trials",
    "run_matched_timing_benchmark",
    "build_falsification_predictions",
    "TEMPORAL_BENCHMARK_SCHEMA_VERSION",
    "LEARNED_BASIS_ID",
    "MATCHED_EXPONENTIAL_ID",
    "DEFAULT_RETENTION_DEFINITIONS",
    "TEMPORAL_CODESIGN_PROVENANCE",
    "eligibility_kernel",
    "preferred_lag",
    "build_temporal_attribution_trials",
    "fit_learned_temporal_basis",
    "run_temporal_attribution_benchmark",
    "structural_resource_table",
    "digital_cost_equivalent",
    "timing_phase_envelope",
    "build_codesign_reference",
    "write_codesign_artifacts",
    "render_codesign_figure",
    # neurons
    "lif_step",
    "lif_step_batched",
    # learning
    "signed_coincidence",
    "unsigned_coincidence",
    "coincidence_drive",
    "three_factor_update",
    "RewardBaseline",
    "SIGNED_RULE_PROVENANCE",
    "THREE_FACTOR_PROVENANCE",
    # bandit / RL task
    "GateBankBatched",
    "LinearErlangGateBankBatched",
    "AbstractTrace",
    "train",
    "reward_rate",
    "trials_to_criterion",
    "W_INIT",
    "W_MAX",
    "run_reversal",
    "run_reversal_grid",
    "calibrate_reversal_scales",
    "run_learning_and_window",
    "run_scaling",
    "run_remedies",
    "run_signed_rule_ablations",
    "BANDIT_METHOD_PROVENANCE",
    # distal-reward credit-assignment tasks (Figs 4, 5)
    "trace_kernel",
    "abstract_kernel",
    "train_trace_level",
    "SpikingGateBank",
    "LinearErlangSpikingGateBank",
    "train_spiking",
    "cue_saturation",
    "run_trace_window",
    "run_spiking_saturation",
    "trace_ratio",
    # multi-decision and historical delayed-choice tasks
    "ActionSequenceTrack",
    "DelayedCuedChoice",
    "ConventionalRstdpTrace",
    "ShallowEpropPolicyTrace",
    "calibrate_comparator_scales",
    "tune_comparator_learning_rates",
    "run_action_sequence",
    "run_delayed_cued_choice",
    "run_retention_delay_curve",
    "run_retention_delay_curve_adaptive",
    # deprecated compatibility names
    "TMaze",
    "EpropTrace",
    "run_sequential",
    "run_dmax_law",
    "run_dmax_adaptive",
    # additional distal-credit tasks
    "run_long_horizon",
    "run_long_horizon_faults",
    "running_rate",
    "interp_dmax",
    # deep / multi-layer crossbar tasks (deep-local, DMS, array scaling)
    "run_deep_local",
    "run_deep_dms",
    "calibrate_dms_scales",
    "tune_dms_learning_rates",
    "run_array_scale",
    "run_dms",
    "run_dms_all",
    "final_rate",
    "main",
    "DEEP_METHOD_PROVENANCE",
    # distal-cue working-memory task
    "run_distal_cue",
    "distal_cue_main",
    "DISTAL_CUE_METHOD_PROVENANCE",
    # probabilistic selection (choose-A / avoid-B)
    "run_probselect",
    "PST_HP",
    "PST_HOMEO",
    "PST_SEEDS",
    "PST_TRIALS",
    "PST_CHANCE",
    "PST_CRIT",
    "PST_METHOD_PROVENANCE",
    # DANDI 001340 preparation and action-contingent logged replay
    "DANDISET_ID",
    "DANDISET_VERSION",
    "DANDI001340_METHOD_PROVENANCE",
    "AssetRecord",
    "LoggedSession",
    "asset_manifest",
    "airpls",
    "robust_reference_regression",
    "preprocess_photometry",
    "download_dandi001340",
    "prepare_dandi001340",
    "load_logged_session",
    "REPLAY_CONDITIONS",
    "ReplayParameters",
    "trial_modulators",
    "run_logged_replay",
    "evaluate_logged_replay_loso",
    "write_replay_artifacts",
    # descriptive EEG helpers (never injected into learning)
    "load_eeg_subject",
    "epoch_feedback",
    "rewp_features",
    "decode_eeg_reward",
    "FRONTOCENTRAL",
    "EEG_METHOD_PROVENANCE",
    # interval selectivity / vector timer
    "run_interval_selectivity",
    "run_vector_timer",
    "peak_lag",
    "selectivity_ratio",
    "aliasing_pair",
    "run_interval",
    "SELECTIVITY_METHOD_PROVENANCE",
    "PREDICTIVE_DELAY_GRID",
    # extensions (multi-timescale, WM+STC, device-TD, beta sensitivity)
    "run_multitimescale",
    "run_wm_stc",
    "wm_isolated",
    "run_device_td",
    "run_beta_sensitivity",
    "load_measured_tau",
    "CHANCE",
    "CRIT",
    "TAU_BAND",
    "BETAS",
    "V_INIT",
    "V_MAX",
    "ETA_V",
    "EXTENSIONS_METHOD_PROVENANCE",
    "RETENTION_DELAY_METHOD_PROVENANCE",
    # hybrid vision front-end + RL readout
    "IMG",
    "C",
    "NOISE",
    "make_grating",
    "make_batch",
    "run_frontend",
    "run_readout_pool",
    "run_hybrid_decision",
    "prep_readouts",
    "run_hybrid_scale",
    "hybrid_final_rate",
    "HYBRID_METHOD_PROVENANCE",
    # statistics
    "bootstrap_ci",
    "summarise",
    # paths / optional fixture and archive resolution
    "paths",
    "data_dir",
    "results_dir",
    "device_model_dir",
    "ITO_PRIMARY_ACQUISITION_DATES",
    "ITO_SUPPLEMENTAL_NEAR_ZERO_FILENAMES",
    "select_ito_source_cohort",
    "publication_device_preflight",
    "save_result",
    "load_result",
]
