r"""Two-state ('second-order') device model: can *capture* be memristive?

This module asks whether the reward-gated **capture** step of the three-factor rule
--- committing the surviving eligibility trace into a lasting weight change ---
can be performed by the device itself, rather than by a peripheral active element.
It does so with a deliberately minimal, provenance-labelled model:

  STATE 1 (the TAG, volatile)  -- the eligibility trace ``v(t)``.
      GROUNDED.  Generated by the fitted :class:`siox_eligibility.device.TransientGate`
      (trap-cascade rise + ``tau_leak`` leakage; KWW field-acceleration laws from
      Chapter 5 / ``kww_final.json``; ``tau_leak`` from the ITO discharge set, median
      ~1.3 s).  No new parameters.

  STATE 2 (the captured WEIGHT, non-volatile) -- the stored conductance ``G``.
      GROUNDED.  The reachable conductance ladder is the *measured* SiO_x multistate
      set used for inference in vu2024snn (``SiO_x-multistate-data.mat``): 53 states,
      G_off ~ 2.7 uS to G_on ~ 3.5 mS (~1300x range).  A capture event moves ``G`` by
      a fraction of one measured step; weights are bounded by the measured ladder.

  THE COUPLING ``g(v)`` -- how strongly a reward pulse writes, given surviving trace.
      *** ASSUMED (the single free element of this model). ***
      A monotonic, saturating gate: capture is proportional to the trace still present
      when the reward arrives.  Motivated by trap-assisted switching --- the trapped
      charge that *is* the tag lowers the local barrier / seeds the SET --- but the
      coefficient is NOT fitted to a measurement.  This is the one law the
      delta-G-vs-delay experiment (manuscript Limitations) would pin down.

Mechanism class precedent (volatile internal state gating a non-volatile write):
second-order memristors and STP->LTP consolidation, demonstrated across material
systems --- Kim/Lu Nano Lett. 2015 (10.1021/acs.nanolett.5b00697); Chang/Lu ACS
Nano 2011 (10.1021/nn202983n); Ohno et al. Nat. Mater. 2011 (10.1038/nmat3054);
Wang et al. Nat. Mater. 2016 (10.1038/nmat4756).  None is SiO_x: whether *this*
material realises the coupling is the open question the model frames, not a result.

The headline observable is the **capture curve**: the committed weight change as a
function of action->reward delay ``D``.  A correct tag-and-capture device commits
change in proportion to the surviving trace and commits ~nothing once ``D`` exceeds
``tau_leak`` --- the physical signature of a capture window set by the tag lifetime.
"""
from __future__ import annotations

import os
from dataclasses import dataclass

import numpy as np

from .device import TransientGate

__all__ = [
    "load_measured_conductance_ladder",
    "CouplingModel",
    "TwoStateSynapse",
    "capture_curve",
]

# Path to the measured multistate conductance data (shared with mnn-torch / vu2024snn).
_DEFAULT_MAT = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..",
                 "mnn-torch", "data", "SiO_x-multistate-data.mat")
)


def load_measured_conductance_ladder(mat_path: str | None = None) -> np.ndarray:
    """Return the sorted *measured* SiO_x conductance levels (S).

    GROUNDED.  Reads the same ``SiO_x-multistate-data.mat`` used for inference in
    vu2024snn and reduces each multistate sweep to a single read conductance
    (median of ``I/V`` over the upper-voltage portion of the 0--0.5 V read sweep).
    """
    from scipy.io import loadmat  # local import: keep module import light

    path = mat_path or _DEFAULT_MAT
    raw = loadmat(path)["data"]            # (799, 3, 53) = [points, I/V/_, states]
    # mirror mnn_torch.devices.load_SiOx_multistate exactly (known-good ordering):
    raw = np.flip(raw, axis=2)
    raw = np.transpose(raw, (1, 2, 0))     # -> (3, states, points)
    raw = raw[:2]                          # -> (2, states, points) = [I, V]
    cur, volt = raw[0], raw[1]
    levels = []
    for s in range(cur.shape[0]):
        v, i = volt[s], cur[s]
        m = (v > 0.05) & np.isfinite(v) & np.isfinite(i)
        if m.sum() > 5:
            levels.append(np.median(i[m] / v[m]))
    return np.array(sorted(levels))


@dataclass
class CouplingModel:
    r"""The ASSUMED capture coupling ``g(v)`` --- the one free element of the model.

    Capture rate per reward pulse is ``kappa * (R - b) * g(v)`` where ``g`` is a
    monotonic saturating function of the surviving trace ``v``:

        g(v) = v**p / (v**p + v_half**p)        (Hill form, p >= 1)

    ``p = 1`` is the plain proportional gate; ``p > 1`` gives a soft threshold
    (capture only once the trace clears ``v_half``).  All three parameters are
    ASSUMED, not fitted; they are the targets of the delta-G-vs-delay measurement.
    """

    kappa: float = 0.6      # capture gain (fraction of a measured G-step per unit reward)
    v_half: float = 0.25    # trace level at half-maximal capture (normalised trace units)
    p: float = 1.0          # Hill exponent: 1 = proportional, >1 = soft threshold

    def g(self, v: np.ndarray | float) -> np.ndarray | float:
        v = np.clip(np.abs(v), 0.0, None)
        vp = v ** self.p
        return vp / (vp + self.v_half ** self.p)


class TwoStateSynapse:
    r"""One synapse with a volatile tag and a non-volatile captured weight.

    The tag ``v(t)`` is the fitted device transient (:class:`TransientGate`).  The
    weight ``G`` lives on the measured conductance ladder and only moves when a
    reward pulse arrives, by an amount gated by the surviving tag through the
    assumed :class:`CouplingModel`.  Sign of ``(R - b)`` sets SET vs RESET; the
    weight is clipped to the measured ``[G_off, G_on]`` bounds.
    """

    def __init__(self, V: float = 0.9, tau_leak: float = 2.0, dt: float = 0.05,
                 coupling: CouplingModel | None = None,
                 ladder: np.ndarray | None = None):
        self.gate = TransientGate(V=V, tau_leak=tau_leak, dt=dt)
        self.coupling = coupling or CouplingModel()
        self.ladder = load_measured_conductance_ladder() if ladder is None else ladder
        self.g_off, self.g_on = float(self.ladder[0]), float(self.ladder[-1])
        # one measured step ~ median spacing of the ladder (in S)
        self.g_step = float(np.median(np.diff(self.ladder)))
        self.dt = dt
        self.reset()

    def reset(self) -> None:
        self.gate.reset()
        self.G = 0.5 * (self.g_off + self.g_on)   # start mid-ladder

    def run(self, t_grid: np.ndarray, coincidence_at: float, reward_at: float,
            reward: float = 1.0, coincidence_dur: float = 0.2,
            reward_dur: float = 0.2) -> dict:
        """Drive a coincidence at ``coincidence_at`` and a reward pulse at ``reward_at``.

        Returns time series of the tag ``v`` and weight ``G``, and the committed
        change ``dG`` (final minus initial).  ``reward`` is the signed ``(R - b)``.
        """
        t_grid = np.asarray(t_grid, float)
        v_ts = np.zeros_like(t_grid)
        G_ts = np.zeros_like(t_grid)
        G0 = self.G
        captured = False     # one reward pulse -> one capture event (impulse model)
        for n, tt in enumerate(t_grid):
            drive = 1.0 if coincidence_at <= tt < coincidence_at + coincidence_dur else 0.0
            v = self.gate.step(drive)            # advance the tag (grounded)
            v_ts[n] = v
            # capture: a single write at reward onset, gated by the surviving tag.
            # Applying it once (not per-dt) makes dG independent of the grid spacing,
            # and matches one reward pulse committing one weight change.
            if (not captured) and tt >= reward_at:
                dG = (self.coupling.kappa * reward
                      * self.coupling.g(v) * self.g_step)
                self.G = float(np.clip(self.G + dG, self.g_off, self.g_on))
                captured = True
            G_ts[n] = self.G
        return {"t": t_grid, "v": v_ts, "G": G_ts, "dG": self.G - G0, "G0": G0}


def capture_curve(delays: np.ndarray, V: float = 0.9, tau_leak: float = 2.0,
                  reward: float = 1.0, dt: float = 0.05,
                  coupling: CouplingModel | None = None,
                  ladder: np.ndarray | None = None) -> dict:
    """Committed weight change ``dG`` vs action->reward delay ``D``.

    For each delay the coincidence fires at a fixed time and the reward pulse
    arrives ``D`` seconds later.  The capture window is expected to follow the tag:
    ``dG`` falls off as ``D`` approaches and exceeds ``tau_leak``.
    """
    delays = np.asarray(delays, float)
    dG = np.zeros_like(delays)
    v_at_reward = np.zeros_like(delays)
    coincidence_at = 1.0
    pad = 1.0
    for i, D in enumerate(delays):
        syn = TwoStateSynapse(V=V, tau_leak=tau_leak, dt=dt,
                              coupling=coupling, ladder=ladder)
        reward_at = coincidence_at + D
        t_end = reward_at + max(0.5, pad)
        t_grid = np.arange(0.0, t_end, dt)
        out = syn.run(t_grid, coincidence_at=coincidence_at, reward_at=reward_at,
                      reward=reward)
        dG[i] = out["dG"]
        # tag value at the moment the reward arrives (for the v vs dG check)
        ridx = int(round(reward_at / dt))
        v_at_reward[i] = out["v"][min(ridx, len(out["v"]) - 1)]
    return {"D": delays, "dG": dG, "v_at_reward": v_at_reward,
            "tau_leak": tau_leak, "g_off": syn.g_off, "g_on": syn.g_on}
